[[main]]
  identifier = 'home'
  name = 'Home'
  pageRef = '/'
  weight = 10

[[main]]
  identifier = 'posts'
  name = 'Posts'
  pageRef = '/posts'
  weight = 20

[[main]]
  identifier = 'tags'
  name = 'Tags'
  pageRef = '/tags'
  weight = 30
